when:
- event: [push]
  branch: main
steps:
- name: build
  image: docker:latest
  commands:
  - docker build -t docker-registry.efhd.dev/homeagent:latest .
  - docker push docker-registry.efhd.dev/homeagent:latest
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
